### ISSUE TITLE
the pretrained model on cityscapes

### ISSUE THREAD

**Issue by xuxiuzhi2627** [xiaoyufenfei/LEDNet#28]
could you send the pretrained model of cityscapes to me? my email address is 2627084603@qq.com
thank you!

**Comment by bernardomig** [comment]
If you can get the models, please dm me! my email is bernardo.lourenco@ua.pt

**Comment by ABDULMAWLA** [comment]
could you send the pretrained model of cityscapes to me? my email address is 210784457@qq.com
thank you!

**Comment by ABDULMAWLA** [comment]
Hello guys 
when I trained the LEDNet on cityscapes, I got this problem

========== ENCODER TRAINING ===========
/home/akram/dataset/cityscapes/leftImg8bit/train
/home/akram/dataset/cityscapes/leftImg8bit/val
----- TRAINING - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@H -----
<class 'utils.loss.CrossEntropyLoss2d'>
----- TRAINING - EPOCH 1 -----
LEARNING RATE:  0.0005
----- TRAINING - EPOCH 1 <torch.utils.data.dataloader.DataLoader object at 0x7fb3f9c15f98> -----
Traceback (most recent call last):
  File "main.py", line 511, in <module>
    main(parser.parse_args())
  File "main.py", line 465, in main
    model = train(args, model, True) #Train encoder
  File "main.py", line 212, in train
    for step, (_,images, labels) in enumerate(loader):
  File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/akram/aa/LEDNet/utils/dataset.py", line 86, in __getitem__
    filenameGt = self.filenamesGt[index]
IndexError: list index out of range

**Comment by RachelJuly** [comment]
If you can get the models, please email me! thanks so much . my email is racheljuly@163.com

**Comment by Benjiaminh** [comment]
> Hello guys
> when I trained the LEDNet on cityscapes, I got this problem
> 
> ========== ENCODER TRAINING ===========
> /home/akram/dataset/cityscapes/leftImg8bit/train
> /home/akram/dataset/cityscapes/leftImg8bit/val
> ----- TRAINING - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@h -----
> <class 'utils.loss.CrossEntropyLoss2d'>
> ----- TRAINING - EPOCH 1 -----
> LEARNING RATE: 0.0005
> ----- TRAINING - EPOCH 1 <torch.utils.data.dataloader.DataLoader object at 0x7fb3f9c15f98> -----
> Traceback (most recent call last):
> File "main.py", line 511, in
> main(parser.parse_args())
> File "main.py", line 465, in main
> model = train(args, model, True) #Train encoder
> File "main.py", line 212, in train
> for step, (_,images, labels) in enumerate(loader):
> File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in **next**
> return self._process_next_batch(batch)
> File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> IndexError: Traceback (most recent call last):
> File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/akram/aa/LEDNet/utils/dataset.py", line 86, in **getitem**
> filenameGt = self.filenamesGt[index]
> IndexError: list index out of range



> Hello guys
> when I trained the LEDNet on cityscapes, I got this problem
> 
> ========== ENCODER TRAINING ===========
> /home/akram/dataset/cityscapes/leftImg8bit/train
> /home/akram/dataset/cityscapes/leftImg8bit/val
> ----- TRAINING - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@h -----
> <class 'utils.loss.CrossEntropyLoss2d'>
> ----- TRAINING - EPOCH 1 -----
> LEARNING RATE: 0.0005
> ----- TRAINING - EPOCH 1 <torch.utils.data.dataloader.DataLoader object at 0x7fb3f9c15f98> -----
> Traceback (most recent call last):
> File "main.py", line 511, in
> main(parser.parse_args())
> File "main.py", line 465, in main
> model = train(args, model, True) #Train encoder
> File "main.py", line 212, in train
> for step, (_,images, labels) in enumerate(loader):
> File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in **next**
> return self._process_next_batch(batch)
> File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> IndexError: Traceback (most recent call last):
> File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/akram/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/akram/aa/LEDNet/utils/dataset.py", line 86, in **getitem**
> filenameGt = self.filenamesGt[index]
> IndexError: list index out of range

I have encountered this problem before. Although this is solved now, I have encountered other problems. Can I communicate with each other?

**Comment by ffyAI** [comment]
请问哪位朋友有LEDNet的预训练模型，有的话，能不能给我发一下，我的邮箱1029692561@qq.com,十分感谢

**Comment by Th8646** [comment]
> could you send the pretrained model of cityscapes to me? my email address is [2627084603@qq.com](mailto:2627084603@qq.com) thank you!



> 
请问你拿到了预训练模型吗

**Comment by RachelJuly** [comment]
Thanks very much. I don’t need it anymore.have a good day

在 2022-04-19 15:07:19，Th8646 ***@***.***> 写道：


could you send the pretrained model of cityscapes to me? my email address is ***@***.*** thank you!

请问你拿到了预训练模型吗
