### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Benjiaminh** [xiaoyufenfei/LEDNet#31]
THCudaCheck FAIL file=/pytorch/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu line=134 error=710 : device-side assert triggered
Traceback (most recent call last):
  File "train/main.py", line 519, in <module>
    main(parser.parse_args())
  File "train/main.py", line 473, in main
    model = train(args, model, True) #Train encoder
  File "train/main.py", line 237, in train
    loss = criterion(outputs, targets[:, 0])    
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/LEDNet/utils/loss.py", line 15, in forward
    return self.loss(F.log_softmax(outputs, dim=1), targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 211, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu:134

**Comment by Benjiaminh** [comment]
my fault

**Comment by ghost** [comment]
@Benjiaminh I have the same issue. How did you fix?

**Comment by Benjiaminh** [comment]
解决了，你解决没
